### ISSUE TITLE
--auto-publish return 400 error

### ISSUE THREAD

**Issue by volodyad** [DrewML/chrome-webstore-upload-cli#12]
When i try to run publish with autopublish like here
webstore upload --auto-publish --source extension.zip --extension-id $EXTENSION_ID --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token $REFRESH_TOKEN

it returns Response code 400 (Bad Request)

**Comment by bfred-it** [comment]
#10 and have a look at the guide. You might be using the wrong keys: https://github.com/bfred-it/chrome-webstore-upload/blob/aae21046d0ae214769993fc7294e34dd3bc23857/How%20to%20generate%20Google%20API%20keys.md

**Comment by bfred-it** [comment]
Try 1.1.1 to see the full error.

**Comment by shroudedcode** [comment]
@bfred-it Could it be that we're experiencing the same issues with the [Refined GitHub](https://github.com/sindresorhus/refined-github) builds? [The last four CRON builds](https://travis-ci.org/sindresorhus/refined-github/builds) failed because of this error resulting in the Chrome version not being published:

```
> @ release:cws /home/travis/build/sindresorhus/refined-github
> cd distribution && webstore upload --auto-publish
Response code 400 (Bad Request)
{
    "error": "invalid_request",
    "error_description": "Parameter not allowed for this message type: redirect_uri"
}
```

---

Quote from [a StackOverflow answer on an issue with the same error](https://stackoverflow.com/a/48943348/6662225):

> It seems Google has recently changed the url for getting a new access token from a refresh token. The older url was https://accounts.google.com/o/oauth2/token and the new one is https://www.googleapis.com/oauth2/v4/token.

**Comment by bfred-it** [comment]
No, that's https://github.com/DrewML/chrome-webstore-upload/pull/14 soon to be published.

**Comment by guillaumevincent** [comment]
hello @bfred-it,
you can probably close this one since DrewML/chrome-webstore-upload#14 is merged
